name: rectangular_stepper
description: "A customizable and visually appealing widget for creating horizontal step indicators with support for sub-steps."
version: 1.0.7

homepage: https://github.com/mossssama
repository: https://github.com/mossssama/RectangularStepper.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1